### ISSUE TITLE
Handover for Instant Win Egypt

### ISSUE THREAD

**Issue by Naguib-ARPU** [ARPU-PLUS/Pipeline#119]
#### @hamedm296 Make sure to take notices and understand everything very well as you will be the sole responsible on this project for any required modifications, investigations or updates :)

Make sure these points are covered and check marked when done:
- [x] Business Logic.
- [x] Code & TFS access.
- [x] Install and get the project run on Mohamed PC.
- [x] Run code on Mohamed PC and let him try to debug something in the flow.
- [x] Code structure.
- [x] Prize module.
- [x] Database & its structure.
- [ ] Admin interface.
- [ ] Fawry prize engine.
- [x] Fawry API. 
- [x] Hosting on the server for Admin
- [x] Hosting on the server for Instant Win.
- [x] Winners flow. what messages the user receive and how.
- [x] How to investigate a complain that the user won but didn't receive a message.
- [ ] SQL Jobs.
- [x] Framework 7 and how it works.
- [x] How front-end and back-end are communicating and the authentication API.
- [x] How pages are created in case need to add new page. 
- [x] Communication messages.
- [x] Prize distribution table and sheet.

**Comment by hamedm296** [comment]
Start 15-12-2019 From 4~5:30
