### ISSUE TITLE
Jawwal Palestine SQL Job for Sending Revenue and Gross Margin to SARA Team

### ISSUE THREAD

**Issue by Weshahi** [ARPU-PLUS/Pipeline#17]

**Comment by Naguib-ARPU** [comment]
@Weshahi This is the equation:

Our Revenues = (Number of billed subscribers X 0.42) in ILS
To convert to USD, divide this by 3.52

**Comment by Naguib-ARPU** [comment]
@Weshahi Reply on the mail thread confirming that the integration is done.
