### ISSUE TITLE
Create new page to show sendout details

### ISSUE THREAD

**Issue by Naguib-ARPU** [ARPU-PLUS/Pipeline#28]
The page should shows same information like the previous page in addition to a graph for traffic details.

**Comment by Weshahi** [comment]
SendOut Start Date
SendOut EndDate
Some Sendout Data in previous Page
Graph per hour 

Subscribers Count (from Transaction Gossip API) based on Service Id , ShortCode , OperatorId 
Sent Conversion = > sub subscribers/ total send out * 100
DLR Conversion => subscribers /  total Delivered DLR  * 100
