### ISSUE TITLE
Category Pages should be read from DB

### ISSUE THREAD

**Issue by Naguib-ARPU** [ARPU-PLUS/Pipeline#403]
Category Pages should be read from DB and get the categorizes correctly from DB.

Each game should have CategoryID column in the games table and these categories should be in look up table.

**Comment by hamedm296** [comment]
مغامرة الباحث عن الناجيت
اركن سيارتك
ضربات جزاء
بيجي بانك مغامرة
بيجي بانك مغامرة
انبوب البيرة
حفلة البيتزا

this games doesn't have category

**Comment by Naguib-ARPU** [comment]
@hamedm296 You can leave it without category or create new category call "General"
