### ISSUE TITLE
Change the Games image URL

### ISSUE THREAD

**Issue by Naguib-ARPU** [ARPU-PLUS/Pipeline#434]
Change the Games image URL to use the Handler instead of plain image URL and that's to minimize the image size

You will need to deploy the Image server handler after Omar finishs it.

**Comment by hamedm296** [comment]
we will publish it in .26 Too ?

**Comment by Naguib-ARPU** [comment]
@hamedm296 You will publish it only on .26 no need to call publish it on .168 you can publish it on .26 and call it from .168
