### ISSUE TITLE
Deply USSD handler on 10.2.10.166 for testing

### ISSUE THREAD

**Issue by Naguib-ARPU** [ARPU-PLUS/Pipeline#458]
Deply USSD handler on 10.2.10.166 on 43043 port for testing with orange and make sure it works as it will be used by Orange Team to do testing

**Comment by hamedm296** [comment]
this port is used before

**Comment by Naguib-ARPU** [comment]
@hamedm296 maho da el port ely ana 3amlo 3ashan el project da fa ana kont 7agzo leh. you can deploy on this porject path

**Comment by hamedm296** [comment]
@Naguib-ARPU  Done but now the problem with .net framework in this server

**Comment by Naguib-ARPU** [comment]
@hamedm296  Plz update

**Comment by hamedm296** [comment]
am testing it now
